services:
  mysql:
    image : mysql:8.0
    ports:
      - "33061:3306"
    volumes:
      - ~/db/mysql:/var/lib/mysql
    environment:
      TERM: xterm
      APP_ENV: dev
      MYSQL_ROOT_PASSWORD: Password4
    container_name: mysql-db